name: Publish Package on Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          fetch-depth: 0
      - name: Node
        uses: actions/setup-node@v2 # set up node 12 on the machine
        with:
          node-version: '12'

      # install dependencies
      - name: Install ğŸ”§
        run: npm install

      # test components
      - name: Test ğŸ§ª
        run: npm run test
        env:
          CI: true

     # build package bundle
      - name: Build ğŸ› 
        run: npm run build

     # create the github release
      - name: Release
        uses: justincy/github-action-npm-release@2.0.2
        id: release

      - name: Print release output
        if: ${{ steps.release.outputs.released == 'true' }}
        run: echo Release ID ${{ steps.release.outputs.release_id }}

      # Publish the package
      - name: Publish the package
        if: ${{ steps.release.outputs.released == 'true' }}
        run: npm publish --access public
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN_DTSSTN }}
